name: "MkDocs Deploy"
description: "Build and publish your MkDocs documentation on GitHub Pages"
author: "yodamad"
branding:
  icon: "upload-cloud"
  color: "green"

inputs:
  output-dir:
    description: "Directory containing the static site output (relative to repo root)"
    required: true
    default: "public"
  workdir:
    description: "Working directory inside the container"
    required: true
    default: "."
    
runs:
  using: "ubuntu-latest"
  steps:
    - name: Install requirements
      run: pip install -r requirements.txt

    - name: Deploy to GitHub Pages
      run: mkdocs gh-deploy --force
