name: "MkDocs Deploy"
description: "Build and publish your MkDocs documentation on GitHub Pages"
author: "yodamad"
branding:
  icon: "upload-cloud"
  color: "green"

inputs:
  output-dir:
    description: "Directory containing the static site output (relative to repo root)"
    required: true
    default: "public"
  workdir:
    description: "Working directory inside the container"
    required: true
    default: "."

runs:
  using: "composite"
  steps:
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Install requirements
        shell: bash
        run: |
          if [[ -f requirements.txt ]]; then
            pip install -r requirements.txt
          else
            pip install mkdocs
          fi

          if [[ -x "$(command -v mkdocs)" ]]; then
            echo "MkDocs is installed"
          else
            echo "MkDocs is not installed"
            exit 1
          fi

      - name: Build documentation
        run: mkdocs build

      - name: Verify output directory exists and is not empty
        shell: bash
        run: |
          set -euo pipefail
          test -d "${{ inputs.output-dir }}"
          test -n "$(ls -A "${{ inputs.output-dir }}")" || { echo "Output dir is empty"; exit 1; }

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ inputs.output-dir }}

      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v4
